# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace

-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        args: ["-x", "-a"]

-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint
        args: ["--disable", "MD013", "MD041", "--"]
         # MD041 disabled because pandoc requires first line to be a metadata block
         # while markdownlint want it to be a level 1 header

-   repo: https://github.com/PyCQA/flake8
    rev: 7.1.0
    hooks:
    -   id: flake8
        args: ["-j8", "--ignore=B036,B902"]
        additional_dependencies: [
            'flake8-blind-except',
            'flake8-docstrings',
            'flake8-bugbear',
            'flake8-comprehensions',
            'flake8-docstrings',
            'flake8-implicit-str-concat',
            'pydocstyle>=5.0.0',
        ]

-   repo: https://github.com/packit/pre-commit-hooks
    rev: v1.2.0
    hooks:
    -   id: validate-config

-   repo: https://github.com/sourcery-ai/sourcery
    rev: "v1.40.0"
    hooks:
    -   id: sourcery
        args: ["--check"]
        exclude: ^(demos/|tests/|oci-hooks/tests/)
